# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

volumes:
  orderer.bct.mat:
  peer0.org1.bct.mat:
  peer0.org2.bct.mat:

networks:
  test:

services:
  orderer.bct.mat:
    container_name: orderer.bct.mat
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.bct.mat:9443
      - ORDERER_METRICS_PROVIDER=prometheus
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/bct.mat/orderers/orderer.bct.mat/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/bct.mat/orderers/orderer.bct.mat/tls/:/var/hyperledger/orderer/tls
      - orderer.bct.mat:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 9443:9443
    networks:
      - test

  peer0.org1.bct.mat:
    container_name: peer0.org1.bct.mat
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.bct.mat:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org1.bct.mat
      - CORE_PEER_ADDRESS=peer0.org1.bct.mat:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.bct.mat:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.bct.mat:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.bct.mat:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/org1.bct.mat/peers/peer0.org1.bct.mat/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/org1.bct.mat/peers/peer0.org1.bct.mat/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.bct.mat:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - test

  peer0.org2.bct.mat:
    container_name: peer0.org2.bct.mat
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org2.bct.mat:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org2.bct.mat
      - CORE_PEER_ADDRESS=peer0.org2.bct.mat:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.bct.mat:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.bct.mat:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.bct.mat:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/org2.bct.mat/peers/peer0.org2.bct.mat/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/org2.bct.mat/peers/peer0.org2.bct.mat/tls:/etc/hyperledger/fabric/tls
      - peer0.org2.bct.mat:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    networks:
      - test
